export const categoryChoices = [
	{ key: 9, text: 'General Knowledge' },
	{ key: 10, text: 'Books' },
	{ key: 11, text: 'Film' },
	{ key: 12, text: 'Music' },
	{ key: 13, text: 'Musicals & Theatres' },
	{ key: 14, text: 'Television' },
	{ key: 15, text: 'Video Games' },
	{ key: 16, text: 'Board Games' },
	{ key: 17, text: 'Science & Nature' },
	{ key: 18, text: 'Computers' },
	{ key: 19, text: 'Mathematics' },
	{ key: 20, text: 'Mythology' },
	{ key: 21, text: 'Sports' },
	{ key: 22, text: 'Geography' },
	{ key: 23, text: 'History' },
	{ key: 24, text: 'Politics' },
	{ key: 25, text: 'Art' },
	{ key: 26, text: 'Celebrities' },
	{ key: 27, text: 'Animals' },
	{ key: 28, text: 'Vehicles' },
	{ key: 29, text: 'Comics' },
	{ key: 30, text: 'Gadgets' },
	{ key: 31, text: 'Japanese Anime & Manga' },
	{ key: 32, text: 'Cartoon & Animations' },
];
